[build]
  command = "corepack enable && yarn install --frozen-lockfile && yarn workspace @metalmaster/shared build && yarn workspace @metalmaster/shared-types build && yarn workspace @metalmaster/shared-validation build && yarn workspace @metalmaster/shared-schemas build && yarn workspace @metalmaster/web build"
  functions = "netlify/functions"
  targetPort = 3003
[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    appDir = "packages/web"

[dev]
  command = "yarn workspace @metalmaster/web dev"
  targetPort = 3000
  functions = "netlify/functions"
