// Auto-generated by scripts/generate-tab-demos.js
// Do not edit manually. Run `yarn workspace @metalmaster/web run generate:tab-demos` to regenerate.
export type GeneratedDemoFile = { label: string; path: string; description?: string; backingUrl?: string; };
export const demoFiles: GeneratedDemoFile[] = [
  {
    "label": "Lesson 01 (ALPHATEX)",
    "path": "/lessons/Lesson01.alphaTex",
    "description": ""
  },
  {
    "label": "Lesson 02 (ALPHATEX)",
    "path": "/lessons/Lesson02.alphaTex",
    "description": ""
  },
  {
    "label": "Lesson 03 (ALPHATEX)",
    "path": "/lessons/Lesson03.alphaTex",
    "description": ""
  },
  {
    "label": "Lesson 04 (ALPHATEX)",
    "path": "/lessons/Lesson04.alphaTex",
    "description": ""
  },
  {
    "label": "Lesson 05 (ALPHATEX)",
    "path": "/lessons/Lesson05.alphaTex",
    "description": ""
  },
  {
    "label": "Lesson 06 (ALPHATEX)",
    "path": "/lessons/Lesson06.alphaTex",
    "description": ""
  },
  {
    "label": "Lesson 07 (ALPHATEX)",
    "path": "/lessons/Lesson07.alphaTex",
    "description": ""
  },
  {
    "label": "Lesson 08 (ALPHATEX)",
    "path": "/lessons/Lesson08.alphaTex",
    "description": ""
  },
  {
    "label": "Lesson 09 (ALPHATEX)",
    "path": "/lessons/Lesson09.alphaTex",
    "description": ""
  },
  {
    "label": "Lesson 10 (ALPHATEX)",
    "path": "/lessons/Lesson10.alphaTex",
    "description": ""
  },
  {
    "label": "Lesson 4 (GP5)",
    "path": "/lessons/Lesson 4.gp5",
    "description": ""
  }
];
